### ISSUE TITLE
Truncated output get-parent-taxid-of-blacklist.py

### ISSUE THREAD

**Issue by sanderdebacker** [GW-HIVE/filtered_nt#10]
In line 60 of get-parent-taxid-of-blacklist.py:
`with open(taxIdFile, "w") as FW: `
The 'w' truncates the file with each new taxid it adds to the output, resulting in only one taxid at the end of the process.

I propose to change this to:
`with open(taxIdFile, "a+") as FW:`
This will do the same without truncating the output file with each new taxid it finds to add to the blacklist.

Please share your thoughts.
Cheers!

**Comment by HadleyKing** [comment]
https://github.com/GW-HIVE/filtered_nt/commit/381d62d78906fdde95c78ee62b84d9525d7ecef2
