### ISSUE TITLE
Install FASTA In GW HPC

### ISSUE THREAD

**Issue by HadleyKing** [GW-HIVE/filtered_nt#15]
[FASTA](https://github.com/wrpearson/fasta36)

**Comment by HadleyKing** [comment]
You should not need any admin privileges.  FASTA is happy to run out of any directory, and just needs to know where the data is.

Also note that FASTA can read a library that is a "file of filenames", so you can do some tests with some fraction of the database, and then add more files to the database to increase the size of the search.

Bill Pearson

**Comment by Jgergely11** [comment]
FASTA installed in GW HPC successfully.
